DROP SEQUENCE ESTADO_SEQ;
DROP SEQUENCE CIDADE_SEQ;
DROP SEQUENCE SEXO_SEQ;
DROP SEQUENCE ESPECIE_SEQ;
DROP SEQUENCE RACA_SEQ;
DROP SEQUENCE HISTCLINICO_SEQ;
DROP SEQUENCE TIPOEXAME_SEQ;
DROP SEQUENCE EXAME_SEQ;
DROP SEQUENCE DIAGNOSTICO_SEQ;
DROP SEQUENCE RECEITUARIO_SEQ;
DROP SEQUENCE CONSULTA_SEQ;
DROP SEQUENCE ANIMAL_SEQ;
DROP SEQUENCE DONO_SEQ;

DROP TABLE ANIMAL;
DROP TABLE DONO;
DROP TABLE CIDADE;
DROP TABLE ESTADO;
DROP TABLE SEXO;
DROP TABLE PORTE;
DROP TABLE RACA;
DROP TABLE ESPECIE;
DROP TABLE EXAME;
DROP TABLE TIPOEXAME;
DROP TABLE DIAGNOSTICO;
DROP TABLE RECEITUARIO;
DROP TABLE HISTCLINICO;

DROP TABLE DONO;

CREATE SEQUENCE ESTADO_SEQ
  MINVALUE 1
  MAXVALUE 9999999999
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;
  
  CREATE SEQUENCE CIDADE_SEQ
  MINVALUE 1
  MAXVALUE 9999999999
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;
  
  CREATE SEQUENCE SEXO_SEQ
  MINVALUE 1
  MAXVALUE 9999999999
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE SEQUENCE ESPECIE_SEQ
  MINVALUE 1
  MAXVALUE 9999999999
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;
  
  CREATE SEQUENCE RACA_SEQ
  MINVALUE 1
  MAXVALUE 9999999999
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;
  
  CREATE SEQUENCE PORTE_SEQ
  MINVALUE 1
  MAXVALUE 9999999999
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE; 
  
CREATE SEQUENCE DONO_SEQ
  MINVALUE 1
  MAXVALUE 9999999999
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;
  
CREATE SEQUENCE ANIMAL_SEQ
  MINVALUE 1
  MAXVALUE 9999999999
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;


CREATE SEQUENCE CONSULTA_SEQ
  MINVALUE 1
  MAXVALUE 9999999999
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE SEQUENCE RECEITUARIO_SEQ
  MINVALUE 1
  MAXVALUE 9999999999
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;
  
CREATE SEQUENCE DIAGNOSTICO_SEQ
  MINVALUE 1
  MAXVALUE 9999999999
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;
  
CREATE SEQUENCE EXAME_SEQ
  MINVALUE 1
  MAXVALUE 9999999999
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;
  
CREATE SEQUENCE TIPOEXAME_SEQ
  MINVALUE 1
  MAXVALUE 9999999999
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;
   
CREATE SEQUENCE HISTCLINICO_SEQ
  MINVALUE 1
  MAXVALUE 9999999999
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;


 CREATE TABLE ESTADO
 (
 	ID 				INT 		NOT NULL PRIMARY KEY,
 	NOME			VARCHAR(30)	NOT NULL 	
 );
 
 CREATE TABLE CIDADE
 (
 	ID				INT			NOT NULL PRIMARY KEY,
 	NOME			VARCHAR(50) NOT NULL,
 	ID_ESTADO		INT			NOT NULL,
 	CONTRAINT CIDADE_DONO_FK
 			  FORENING KEY (ID_ESTADO)
 );
 
 CREATE TABLE SEXO
 (
 	ID 				INT 		NOT NULL PRIMARY KEY,
 	DESCRICAO		VARCHAR(15)	NOT NULL 	
 );
 
 CREATE TABLE ESPECIE
 (
 	ID 				INT 		NOT NULL PRIMARY KEY,
 	DESCRICAO		INT 		NOT NULL 	
 );
 
 CREATE TABLE RACA
 (
 	ID 				INT 		NOT NULL PRIMARY KEY,
 	DESCRICAO		VARCHAR(50),
 	
 	ID_ESPECIE 		INT			NOT NULL,
 	CONTRAINT ESPECIE_RACA_FK
 			  FORENING KEY (ID_ESPECIE)
 			  REFERENCES ESPECIE(ID)
 );
 
 CREATE TABLE PORTE
 (
 	ID 				INT 		NOT NULL PRIMERY KEY,
 	DESCICAO		VARCHAR(50) NOT NULL
 ); 
  
CREATE TABLE RECEITUARIO
(
	ID 				 INT   		  NOT NULL PRIMARY KEY,
	DATA			 DATE		  NOT NULL,
	UNMEDIDA		 VARCHAR(50)  NOT NULL,
	PESO			 DECIMAL(3,3) NOT NULL,
	RECEITATEXTO	 VARCHAR(500) NOT NULL
);

CREATE TABLE DIAGNOSTICO
(
	ID 				 INT   		  NOT NULL PRIMARY KEY,
	DATA			 DATE		  NOT NULL,
	UNMEDIDA		 VARCHAR(50)  NOT NULL,
	PESO			 DECIMAL(3,3) NOT NULL,
	DIAGNOSTICOTEXTO VARCHAR(500) NOT NULL
);

CREATE TABLE TIPOEXAME
(
	ID 				 INT 		  NOT NULL PRIMARY KEY,
	DESCRICAO		 VARCHAR(50)  NOT NULL	

);

CREATE TABLE EXAME
(
	ID 				 INT 		  NOT NULL PRIMERY KEY,
	DATA			 DATE		  NOT NULL,
	UNMEDIDA		 VARCHAR(50)  NOT NULL,
	PESO			 DECIMAL(3,3) NOT NULL,
	
	ID_TIPOEXAME	 INT		  NOT NULL,
	CONTRAINT EXAME_TIPOEXAME_FK
			  FOREING KEY(ID_TIPOEXAME)
			  REFERENCES TIPOEXAME(ID)
);

CREATE TABLE HISTCLINICO
(
	ID 				 INT    	  NOT NULL PRIMARY KEY,
	
	ID_RECEITUARIO	 INT		  NOT NULL,
	ID_DIAGNOSTICO	 INT 		  NOT NULL,
	ID_EXAME		 INT 		  NOT NULL,
	CONTRAINT HISTCLINICO_RECEITUARIO_FK
			  FORENING KEY(ID_RECEITUARIO)
			  REFERENCES RECEITUARIO(ID),
	CONTRAINT HISTCLINICO_DIAGNOSTICO_FK
			  FORENING KEY(ID_DIAGNOSTICO)
			  REFERENCES DIAGNOSTICO(ID),
	CONTRAINT HISTCLINICO_EXAME_FK
			  FOREING KEY(ID_EXAME)
			  REFERENCES EXAME(ID)
			  
);

 CREATE TABLE DONO
 (
	ID              INT        	NOT NULL PRIMARY KEY,
	NOME            VARCHAR(90) NOT NULL,
	SEXO            CHAR        NOT NULL,
	DATA_NASCIMENTO	DATE		NOT NULL,
	RG				DECIMAL(10) NOT NULL,
	CPF             DECIMAL(11) NOT NULL,
	TELEFONE        DECIMAL(11) NOT NULL,
	CELULAR			DECIMAL(11)	NOT NULL,
	EMAIL           VARCHAR(100)NOT NULL,
	OBSERVACAO		VARCHAR	    NOT NULL,
	ENDERECO		VARCHAR(100)NOT NULL,
	BAIRRO			VARCHAR(30) NOT NULL,
	CEP				DECIMAL(9)	NOT NULL,	
	
	ID_CIDADE		INT 	 	NOT NULL,
	CONTRAINT DONO_CIDADE_FK
			  FOREING KEY (ID_CIDADE)
			  REFERENCES CIDADE(ID)
	
 );
	 
 CREATE TABLE ANIMAL
 (
	ID               INT          NOT NULL PRIMARY KEY,
	NOME             VARCHAR(90)  NOT NULL,
	DATA_NASCIMENTO  DATE         NOT NULL,
	IDADE			 DECIMAL(2)	  NOT NULL,
	ANILHA			 DECIMAL(10)  NOT NULL,
	CONSUMO_RACAO	 DECIMAL(2,3) NOT NULL,
	PELAGEM			 VARCHAR(20)  NOT NULL,
	PEDIGREE		 BOOLEAN	  NOT NULL
	
	ID_DONO			 INT 		  NOT NULL,
	ID_SEXO			 INT          NOT NULL,
	ID_RACA			 INT 		  NOT NULL,
	ID_PORTE		 INT 		  NOT NULL,
	ID_HISTCLINICO	 INT		  NOT NULL,
	CONTRAINT ANIMAL_DONO_FK
	FOREING KEY (ID_DONO)
			  REFERENCES DONO(ID),
	CONTRAINT ANIMAL_SEXO_FK
			  FOREING KEY (ID_SEXO)
			  REFERENCES SEXO(ID),
	CONTRAINT ANIMAL_RACA_FK
			  FOREING KEY (ID_RACA)
			  REFERENCES RACA(ID),
	CONTRAINT ANIMAL_PORTE_FK
			  FOREING KEY (ID_PORTE)
			  REFERENCES PORTE(ID),
	CONTRAINT ANIMAL_HISTCLINICO_FK
			  FOREING KEY (ID_HISTCLINICO)
			  REFERENCES HISTCLINICO(ID)
);

-- CREATE
INSERT INTO DONO (ID,NOME,SEXO,DATA_NASCIMENTO,RG,CFP,TELEFONE,CELULAR,EMAIL,OBSERVACAO,ENDERECO,BAIRRO,CEP,IDCIDADE) VALUES (ANIMAL_SEQ.NEXTVAL, 'Sotravio Gerdercio', '30/09/2000', 3456767, 'sotra@gmail.com', 39654328810);

-- RECOVERY
SELECT ID, NOME, DATA_NASCIMENTO, TELEFONE, EMAIL, CPF FROM ANIMAL WHERE ID = 1;

-- UPDATE
UPDATE ANIMAL SET NOME = 'Sotravio Gerdercio Dosdravio', DATA_NASCIMENTO = '30/08/2000', TELEFONE = 998786767, EMAIL='sotra@outlook.com', CPF=23656743328 WHERE ID = 1;

-- SEARCH
SELECT ID, NOME, DATA_NASCIMENTO, TELEFONE, EMAIL, CPF FROM ANIMAL;

-- DELETE
DELETE FROM ANIMAL WHERE ID = 1;
	
	
	
	
	
	
	
	
	