SET IDENTITY_INSERT [dbo].[Raca] ON
INSERT INTO [dbo].[Raca] ([Id], [Descricao], [EspecieId]) VALUES (1, N'Andotinha', 1)
INSERT INTO [dbo].[Raca] ([Id], [Descricao], [EspecieId]) VALUES (2, N'Bandeirinha', 1)
INSERT INTO [dbo].[Raca] ([Id], [Descricao], [EspecieId]) VALUES (3, N'Coruja', 1)
INSERT INTO [dbo].[Raca] ([Id], [Descricao], [EspecieId]) VALUES (4, N'Degolado', 1)
INSERT INTO [dbo].[Raca] ([Id], [Descricao], [EspecieId]) VALUES (5, N'Quero quero', 1)
INSERT INTO [dbo].[Raca] ([Id], [Descricao], [EspecieId]) VALUES (6, N'Gavião', 1)
INSERT INTO [dbo].[Raca] ([Id], [Descricao], [EspecieId]) VALUES (7, N'Angus', 2)
INSERT INTO [dbo].[Raca] ([Id], [Descricao], [EspecieId]) VALUES (8, N'Caracu', 2)
INSERT INTO [dbo].[Raca] ([Id], [Descricao], [EspecieId]) VALUES (9, N'Nelore', 2)
INSERT INTO [dbo].[Raca] ([Id], [Descricao], [EspecieId]) VALUES (10, N'Akita', 11)
INSERT INTO [dbo].[Raca] ([Id], [Descricao], [EspecieId]) VALUES (11, N'Basset Hound', 11)
INSERT INTO [dbo].[Raca] ([Id], [Descricao], [EspecieId]) VALUES (12, N'Cocker Spaniel Inglês', 11)
INSERT INTO [dbo].[Raca] ([Id], [Descricao], [EspecieId]) VALUES (13, N'Golden Retriever', 11)
INSERT INTO [dbo].[Raca] ([Id], [Descricao], [EspecieId]) VALUES (15, N'Maltês', 11)
INSERT INTO [dbo].[Raca] ([Id], [Descricao], [EspecieId]) VALUES (16, N'Pastor Alemão', 11)
INSERT INTO [dbo].[Raca] ([Id], [Descricao], [EspecieId]) VALUES (17, N'Sem Raça Definida', 11)
INSERT INTO [dbo].[Raca] ([Id], [Descricao], [EspecieId]) VALUES (18, N'Repartida', 3)
INSERT INTO [dbo].[Raca] ([Id], [Descricao], [EspecieId]) VALUES (19, N'Canindé', 3)
INSERT INTO [dbo].[Raca] ([Id], [Descricao], [EspecieId]) VALUES (20, N'Boer', 3)
INSERT INTO [dbo].[Raca] ([Id], [Descricao], [EspecieId]) VALUES (21, N'Holandês', 4)
INSERT INTO [dbo].[Raca] ([Id], [Descricao], [EspecieId]) VALUES (22, N'Dwarf Hotot', 4)
INSERT INTO [dbo].[Raca] ([Id], [Descricao], [EspecieId]) VALUES (23, N'Mini lop', 4)
INSERT INTO [dbo].[Raca] ([Id], [Descricao], [EspecieId]) VALUES (25, N'Polish', 4)
INSERT INTO [dbo].[Raca] ([Id], [Descricao], [EspecieId]) VALUES (26, N'Lion', 4)
INSERT INTO [dbo].[Raca] ([Id], [Descricao], [EspecieId]) VALUES (27, N'American Saddlebred', 5)
INSERT INTO [dbo].[Raca] ([Id], [Descricao], [EspecieId]) VALUES (28, N'Finlandês', 5)
INSERT INTO [dbo].[Raca] ([Id], [Descricao], [EspecieId]) VALUES (29, N'Pônei', 5)
INSERT INTO [dbo].[Raca] ([Id], [Descricao], [EspecieId]) VALUES (30, N'Puro Sangue Lusitano', 5)
INSERT INTO [dbo].[Raca] ([Id], [Descricao], [EspecieId]) VALUES (31, N'Shire', 5)
INSERT INTO [dbo].[Raca] ([Id], [Descricao], [EspecieId]) VALUES (32, N'Abissínio', 6)
INSERT INTO [dbo].[Raca] ([Id], [Descricao], [EspecieId]) VALUES (33, N'Angorá', 6)
INSERT INTO [dbo].[Raca] ([Id], [Descricao], [EspecieId]) VALUES (34, N'Egyptian Mau', 6)
INSERT INTO [dbo].[Raca] ([Id], [Descricao], [EspecieId]) VALUES (35, N'Exótico', 6)
INSERT INTO [dbo].[Raca] ([Id], [Descricao], [EspecieId]) VALUES (36, N'Maine Coon', 6)
INSERT INTO [dbo].[Raca] ([Id], [Descricao], [EspecieId]) VALUES (37, N'Persa', 6)
INSERT INTO [dbo].[Raca] ([Id], [Descricao], [EspecieId]) VALUES (38, N'Scottish Fold', 6)
INSERT INTO [dbo].[Raca] ([Id], [Descricao], [EspecieId]) VALUES (39, N'Dorper', 7)
INSERT INTO [dbo].[Raca] ([Id], [Descricao], [EspecieId]) VALUES (40, N'Merino', 7)
INSERT INTO [dbo].[Raca] ([Id], [Descricao], [EspecieId]) VALUES (41, N'Ryeland', 7)
INSERT INTO [dbo].[Raca] ([Id], [Descricao], [EspecieId]) VALUES (42, N'Texel', 7)
INSERT INTO [dbo].[Raca] ([Id], [Descricao], [EspecieId]) VALUES (43, N'Abelhinha', 8)
INSERT INTO [dbo].[Raca] ([Id], [Descricao], [EspecieId]) VALUES (44, N'Baiacu', 8)
INSERT INTO [dbo].[Raca] ([Id], [Descricao], [EspecieId]) VALUES (45, N'Dojô', 8)
INSERT INTO [dbo].[Raca] ([Id], [Descricao], [EspecieId]) VALUES (46, N'Neon', 8)
INSERT INTO [dbo].[Raca] ([Id], [Descricao], [EspecieId]) VALUES (47, N'Peixe-palhaço', 8)
INSERT INTO [dbo].[Raca] ([Id], [Descricao], [EspecieId]) VALUES (48, N'Tubarão', 8)
INSERT INTO [dbo].[Raca] ([Id], [Descricao], [EspecieId]) VALUES (49, N'Anole Verde', 9)
INSERT INTO [dbo].[Raca] ([Id], [Descricao], [EspecieId]) VALUES (50, N'Boicora', 9)
INSERT INTO [dbo].[Raca] ([Id], [Descricao], [EspecieId]) VALUES (51, N'Cobra-de-vidro', 9)
INSERT INTO [dbo].[Raca] ([Id], [Descricao], [EspecieId]) VALUES (52, N'Jararaca-verde', 9)
INSERT INTO [dbo].[Raca] ([Id], [Descricao], [EspecieId]) VALUES (53, N'Lagarto aranha', 9)
INSERT INTO [dbo].[Raca] ([Id], [Descricao], [EspecieId]) VALUES (54, N'Berkshire', 10)
INSERT INTO [dbo].[Raca] ([Id], [Descricao], [EspecieId]) VALUES (55, N'British Lop', 10)
INSERT INTO [dbo].[Raca] ([Id], [Descricao], [EspecieId]) VALUES (56, N'Cantonense', 10)
INSERT INTO [dbo].[Raca] ([Id], [Descricao], [EspecieId]) VALUES (57, N'Duroc', 10)
SET IDENTITY_INSERT [dbo].[Raca] OFF
