SET IDENTITY_INSERT [dbo].[Estado] ON
INSERT INTO [dbo].[Estado] ([Id], [NMEstado]) VALUES (1, N'AC')
INSERT INTO [dbo].[Estado] ([Id], [NMEstado]) VALUES (2, N'AL')
INSERT INTO [dbo].[Estado] ([Id], [NMEstado]) VALUES (3, N'AP')
INSERT INTO [dbo].[Estado] ([Id], [NMEstado]) VALUES (4, N'AM')
INSERT INTO [dbo].[Estado] ([Id], [NMEstado]) VALUES (5, N'BA')
INSERT INTO [dbo].[Estado] ([Id], [NMEstado]) VALUES (6, N'CE')
INSERT INTO [dbo].[Estado] ([Id], [NMEstado]) VALUES (7, N'DF')
INSERT INTO [dbo].[Estado] ([Id], [NMEstado]) VALUES (8, N'ES')
INSERT INTO [dbo].[Estado] ([Id], [NMEstado]) VALUES (9, N'GO')
INSERT INTO [dbo].[Estado] ([Id], [NMEstado]) VALUES (10, N'MA')
INSERT INTO [dbo].[Estado] ([Id], [NMEstado]) VALUES (11, N'MS')
INSERT INTO [dbo].[Estado] ([Id], [NMEstado]) VALUES (12, N'PA')
INSERT INTO [dbo].[Estado] ([Id], [NMEstado]) VALUES (13, N'PB')
INSERT INTO [dbo].[Estado] ([Id], [NMEstado]) VALUES (14, N'PE')
INSERT INTO [dbo].[Estado] ([Id], [NMEstado]) VALUES (15, N'PI')
INSERT INTO [dbo].[Estado] ([Id], [NMEstado]) VALUES (16, N'PR')
INSERT INTO [dbo].[Estado] ([Id], [NMEstado]) VALUES (17, N'RJ')
INSERT INTO [dbo].[Estado] ([Id], [NMEstado]) VALUES (18, N'RN')
INSERT INTO [dbo].[Estado] ([Id], [NMEstado]) VALUES (19, N'RO')
INSERT INTO [dbo].[Estado] ([Id], [NMEstado]) VALUES (20, N'RR')
INSERT INTO [dbo].[Estado] ([Id], [NMEstado]) VALUES (21, N'SC')
INSERT INTO [dbo].[Estado] ([Id], [NMEstado]) VALUES (22, N'SP')
INSERT INTO [dbo].[Estado] ([Id], [NMEstado]) VALUES (23, N'SE')
INSERT INTO [dbo].[Estado] ([Id], [NMEstado]) VALUES (24, N'TO')
SET IDENTITY_INSERT [dbo].[Estado] OFF
